### PR TITLE
Provide zcorn-averaged cell depth for the cp grid.

### PR DESCRIPTION
**Pull request by osae**
This PR is associated with PR opm-core #862.

### CODE REVIEW

**Comment by blattms** [comment]
There sould be no need to recompute as his information should be readily available:
```c++
return current_view_data_->geomVector<0>()[Entity<0>(*this,cell_index)[nd-1];
```
or
```c++
return this->cellCentroid(cell_index)[nd-1]
```

**Comment by blattms** [comment]
Sorry, I did not read OPM/opm-core#862 first. My suggestion result in the difference that rose the invention of this function. Can someone enlighten me what the difference is? Do UG and CpGrid even use the  same centroid computation?

**Comment by atgeirr** [comment]
> Do UG and CpGrid even use the same centroid computation?

No they don't, and small differences in centroids, areas and volumes could be a significant factor in why the results are different.

**Comment by blattms** [comment]
Agreed. That might explain the difference observed in OPM/opm-autodff#467

**Comment by atgeirr** [comment]
I am currently running a build test on this and the opm-core PR, and will merge if that succeeds. I would appreciate a minor change here though: a copy of the explanatory comment (present in the UnstructuredGrid version) would be good to have here, too.

**Comment by osae** [comment]
OK, I'll copy the comment.

**Pull request merged**
