### PR TITLE
Fix constructor of PersistentContainer for DUNE-grid 2.3 and later.

### PR DESCRIPTION
**Pull request by dr-robertk**
This class does currently not compile with dune-grid-2.3.1 and later. This PR fixes this issue.

### CODE REVIEW

**Comment by bska** [comment]
That's strange.  I've been using this code with Dune grid 2.3.1 for quite some time and I have never seen a build failure (in this part).  Have we not been exercising the branch?

**Comment by dr-robertk** [comment]
Have you used PersistentContainer explicitly? When you compare the code you can already see that this cannot compile.

**Comment by bska** [comment]
> Have you used `PersistentContainer` explicitly?

No, I have not.  That's why I'm asking if we've ever exercised that branch or if we've been shipping broken software since commit 4bf7be6 (PR #42).

**Comment by dr-robertk** [comment]
Other than that everything at least compiles.

**Comment by bska** [comment]
> Other than that everything at least compiles.

Sorry, I don't understand.  Could you add a bit of context to the statement?

**Comment by dr-robertk** [comment]
I mean that besides the issue mentioned above I have not experienced other problems. 
Also, PersistentContainer is a feature that is not used all that much for some reason. That is why this has not been discovered yet. It can be used to attach arbitrary data to the grid. In case of CpGrid is simply used the IndexSet and a std::vector. For other grids this might be different since the IndexSet is not persistent (in terms of grid change).

**Comment by bska** [comment]
> I mean that besides the issue [of this PR] I have not experienced other problems.

So, the practical upshot of this discussion is that we have indeed not been exercising the particular code in mainline dune-cornerpoint and have been shipping broken software since August 2013.  As I was the one to merge PR #42 which introduced this branch interface, I'll have to accept responsibility for missing code review.

**Comment by dr-robertk** [comment]
If you want to put it that way, yes. On the other hand nobody seemed to bother, so no big deal. Anyway, this patch fixes the issue.

**Comment by bska** [comment]
> nobody seemed to bother, so no big deal.

I suppose.  On the other hand, the `1.1 -> Data()` transformation could possibly have been made in a separate commit since that fixes a separate issue (namely generalising the `PersistentContainer` to handle data types other than `double`).

**Comment by bska** [comment]
Oh, by the way, the removal of the constant `1.1` in the `# !DUNE_VERSION_NEWER` branch is wrong.  The Dune 2.2 `PersistentContainerVector` constructor interface is
```C++
PersistentContainerVector( const GridType& grid, const int codim,
                           const Index& index,
                           const double overEstimate,
                           const typename Vector::allocator_type &allocator );
```
so the third parameter must be a `double` rather than a `LeafIndexSet`.

**Comment by dr-robertk** [comment]
Ops. That was an accidental change. Thanks for double checking.

**Comment by dr-robertk** [comment]
Fixed and rebased to make my mistake disappear... ;-)

**Comment by bska** [comment]
> Fixed and rebased to make my mistake disappear... ;-)

Cool.  I've run a few build tests just to make sure that we don't break anything.  I'll merge into master.  Thanks for diagnosing the problem and producing a fix.

**Comment by dr-robertk** [comment]
Thanks

**Pull request merged**
